name = "Vanilla+"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1556f4d8d449c6a3172345a15ea61a5589f5d84a9fbc08e8b60b936b03e8a1fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
